"""
Email Generator: Uses the OpenAI Chat Completions API to draft the body
of a reply email, using as context the most relevant fragments
retrieved from the PDF (RAG).
"""

from typing import List, Dict
from openai import OpenAI


DEFAULT_SYSTEM_PROMPT = """You are an assistant that drafts email replies for a \
company's support/customer service team.

Rules:
- Answer ONLY based on the context information provided below. \
If the context doesn't have the answer, say so honestly and suggest \
escalating the query to a team member — do not make up information.
- Professional, clear and friendly tone.
- Don't add unnecessary generic greetings/sign-offs, get to the point.
- Never reveal that you are using a "context" or a PDF; write as if \
it were the company's own knowledge.
"""


class EmailGenerator:
    """Generates email bodies with GPT, using context retrieved from the PDF"""

    def __init__(self, client: OpenAI, model: str = "gpt-4o-mini",
                 system_prompt: str = DEFAULT_SYSTEM_PROMPT):
        """
        Args:
            client: Already-initialized OpenAI client
            model: Chat model to use (gpt-4o-mini is fast and cheap;
                   use gpt-4o if you need higher writing quality)
            system_prompt: Base style/tone/rules instructions
        """
        self.client = client
        self.model = model
        self.system_prompt = system_prompt

    def _build_context_block(self, retrieved_chunks: List[Dict]) -> str:
        """Builds the context block from the retrieved chunks"""
        if not retrieved_chunks:
            return "(No relevant context found in the knowledge base)"

        blocks = []
        for chunk in retrieved_chunks:
            blocks.append(f"[Page {chunk['page']}]\n{chunk['text']}")
        return "\n\n---\n\n".join(blocks)

    def classify(self, email_subject: str, email_body: str,
                 categories: List[str]) -> str:
        """
        Classifies an incoming email into a predefined category.
        Replaces the old TF-IDF + Naive Bayes classifier.

        Args:
            email_subject: Email subject
            email_body: Email body
            categories: List of possible categories

        Returns:
            Name of the chosen category
        """
        prompt = f"""Classify the following email into ONE of these categories: \
{', '.join(categories)}.

Subject: {email_subject}
Body: {email_body}

Reply with ONLY the exact category name, no explanations."""

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )
        return response.choices[0].message.content.strip()

    def generate_reply(self, email_subject: str, email_body: str,
                        sender_name: str, retrieved_chunks: List[Dict]) -> str:
        """
        Generates the reply body for an email, using context retrieved
        from the PDF (RAG)

        Args:
            email_subject: Subject of the incoming email
            email_body: Body of the incoming email
            sender_name: Name of who wrote the email
            retrieved_chunks: Relevant chunks returned by KnowledgeBase.search()

        Returns:
            Reply email body generated by GPT
        """
        context_block = self._build_context_block(retrieved_chunks)

        user_prompt = f"""CONTEXT (extracted from the internal knowledge base):
{context_block}

---

RECEIVED EMAIL:
From: {sender_name}
Subject: {email_subject}
Body: {email_body}

---

Draft the reply body for this email, using the context above."""

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.4
        )

        return response.choices[0].message.content.strip()
